var MessageList = {
    Rows: [
        {
            "messageCode":"D01S01B11",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"Webサイト",
            "outputMessage":"Webサイトやインターネット広告運用でよく"
        },
         {
            "messageCode":"D01S01B12",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"便宜",
            "outputMessage":"は私の方で便宜的に区分したものです"
        },
         {
            "messageCode":"D01S01B13",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"PV",
            "outputMessage":"PV／セッション（訪問別PV"
        },
         {
            "messageCode":"D01S01B14",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"単価",
            "outputMessage":"CPM（インプレッション単価)"
        },
         {
            "messageCode":"D01S01B15",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務",
            "outputMessage":"CPC（クリック単価"
        },
         {
            "messageCode":"D01S01B16",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事",
            "outputMessage":"ところで、実はこれらの中には「良いKPI」と「悪いKPI」が混在しています"
        },
         {
            "messageCode":"D01S01B17",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"業務_1031_1",
            "outputMessage":""
        },
        {
            "messageCode":"D01S01B18",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"1031_1",
            "outputMessage":""
        },
        {
            "messageCode":"D01S01B19",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"1",
            "outputMessage":""
        },
        {
            "messageCode":"D01S01B20",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事1_1",
            "outputMessage":"この記事を読んだ人にお薦めの記事"
        },
        {
            "messageCode":"D01S01B21",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"この記事を読んだ人にお薦めのホワイトペーパー（TechTargetジャパン）"
        },
        {
            "messageCode":"D01S01B22",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"マーケティング関連の製品情報（TechTargetジャパン)"
        },
        {
            "messageCode":"D01S01B23",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"無理難題に立ち向かうマーケターには「データ」が必要だ"
        },
        {
            "messageCode":"D01S01B24",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"「A8.net」、アフィリエイト参加者に掲載情報の信頼性チェックサービスを提供開始"
        },
        {
            "messageCode":"D01S01B25",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"大量の検索結果をSEOに活かす際の2つの注意点 - ちびクロの細かすぎて伝わらないネットサービスの話"
        },
        {
            "messageCode":"D01S01B26",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"デジタル・ガジェット"
        },
        {
            "messageCode":"D01S01B27",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"Facebook、スムーズなショッピングを促す新広告フォーマット「コレクション」を発表"
        },
        {
            "messageCode":"D01S01B28",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":" ちびクロの細かすぎて伝わらないネットサービスの話"
        },
        {
            "messageCode":"D01S01B29",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"WebアナリストのUX戦略思考"
        },
        {
            "messageCode":"D01S01B30",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"SNSでファンを虜にする方法"
        },
        {
            "messageCode":"D01S01B31",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":""
        },
        {
            "messageCode":"D01S01B41",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"数字が示すエンドポイントセキュリティの実像"
        },
        {
            "messageCode":"D01S01B61",
            "processingDivision":"人事業務_1031_1",
            "outputSegment":"人事業務_1031_1",
            "outputLevel":"人事業務_1031_1",
            "outputMessage":"Googleにとっての“良質なコンテンツ”の定義がハックされた結果"
        }
        ]
       
}