var BaseinfoList = {
	Rows: [{
		"projectId": "D01S01B11",
		"projectName": "prject_1031_1",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B12",
		"projectName": "prject_1031_2",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B13",
		"projectName": "prject_1031_3",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B14",
		"projectName": "prject_1031_4",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B15",
		"projectName": "prject_1031_5",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B16",
		"projectName": "prject_1031_6",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B17",
		"projectName": "prject_1031_7",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B18",
		"projectName": "prject_1031_8",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B19",
		"projectName": "prject_1031_9",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B20",
		"projectName": "prject_1031_10",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B21",
		"projectName": "prject_1031_11",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B22",
		"projectName": "prject_1031_12",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B23",
		"projectName": "prject_1031_13",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B24",
		"projectName": "prject_1031_14",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B25",
		"projectName": "prject_1031_15",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B26",
		"projectName": "prject_1031_16",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B27",
		"projectName": "prject_1031_17",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B28",
		"projectName": "prject_1031_18",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}, {
		"projectId": "D01S01B28",
		"projectName": "prject_1031_19",
		"startTime": "2017/03/28",
		"endTime": "2017/05/28",
		"overview": ""
	}]

}

var UserList = {
	Rows: [{
		"userId": "001",
		"userName": "Jerry1",
		"mailAddress": "jerry1@qq.com",
		"snsAddress": "jerry1@163.com",
		"ruleName": "人事業務_1031_1",
		"memo": "新規登録"
	}, {
		"userId": "002",
		"userName": "Jerry2",
		"mailAddress": "jerry2@qq.com",
		"snsAddress": "jerry2@163.com",
		"ruleName": "人事業務_1031_2",
		"memo": "新規登録"
	}, {
		"userId": "003",
		"userName": "Jerry3",
		"mailAddress": "jerry3@qq.com",
		"snsAddress": "jerry3@163.com",
		"ruleName": "人事業務_1031_3",
		"memo": "新規登録"
	}, {
		"userId": "004",
		"userName": "Jerry4",
		"mailAddress": "jerry4@qq.com",
		"snsAddress": "jerry4@163.com",
		"ruleName": "人事業務_1031_4",
		"memo": "新規登録"
	}, {
		"userId": "005",
		"userName": "Jerry5",
		"mailAddress": "jerry5@qq.com",
		"snsAddress": "jerry5@163.com",
		"ruleName": "人事業務_1031_5",
		"memo": "新規登録"
	}, {
		"userId": "006",
		"userName": "Jerry6",
		"mailAddress": "jerry6@qq.com",
		"snsAddress": "jerry6@163.com",
		"ruleName": "人事業務_1031_6",
		"memo": "新規登録"
	}, {
		"userId": "007",
		"userName": "Jerry7",
		"mailAddress": "jerry7@qq.com",
		"snsAddress": "jerry7@163.com",
		"ruleName": "人事業務_1031_7",
		"memo": "新規登録"
	}, {
		"userId": "008",
		"userName": "Jerry8",
		"mailAddress": "jerry8@qq.com",
		"snsAddress": "jerry8@163.com",
		"ruleName": "人事業務_1031_8",
		"memo": "新規登録"
	}, {
		"userId": "009",
		"userName": "Jerry9",
		"mailAddress": "jerry9@qq.com",
		"snsAddress": "jerry9@163.com",
		"ruleName": "人事業務_1031_9",
		"memo": "新規登録"
	}, {
		"userId": "010",
		"userName": "Jerry10",
		"mailAddress": "jerry10@qq.com",
		"snsAddress": "jerry10@163.com",
		"ruleName": "人事業務_1031_10",
		"memo": "新規登録"
	}, {
		"userId": "011",
		"userName": "Jerry11",
		"mailAddress": "jerry11@qq.com",
		"snsAddress": "jerry11@163.com",
		"ruleName": "人事業務_1031_11",
		"memo": "新規登録"
	}, {
		"userId": "012",
		"userName": "Jerry12",
		"mailAddress": "jerry12@qq.com",
		"snsAddress": "jerry12@163.com",
		"ruleName": "人事業務_1031_12",
		"memo": "新規登録"
	}, {
		"userId": "013",
		"userName": "Jerry13",
		"mailAddress": "jerry13@qq.com",
		"snsAddress": "jerry13@163.com",
		"ruleName": "人事業務_1031_13",
		"memo": "新規登録"
	}, {
		"userId": "014",
		"userName": "Jerry14",
		"mailAddress": "jerry14@qq.com",
		"snsAddress": "jerry14@163.com",
		"ruleName": "人事業務_1031_14",
		"memo": "新規登録"
	}, {
		"userId": "015",
		"userName": "Jerry15",
		"mailAddress": "jerry15@qq.com",
		"snsAddress": "jerry15@163.com",
		"ruleName": "人事業務_1031_16",
		"memo": "新規登録"
	}, {
		"userId": "016",
		"userName": "Jerry16",
		"mailAddress": "jerry16@qq.com",
		"snsAddress": "jerry16@163.com",
		"ruleName": "人事業務_1031_16",
		"memo": "新規登録"
	}, {
		"userId": "017",
		"userName": "Jerry17",
		"mailAddress": "jerry17@qq.com",
		"snsAddress": "jerry17@163.com",
		"ruleName": "人事業務_1031_17",
		"memo": "新規登録"
	}, {
		"userId": "018",
		"userName": "Jerry18",
		"mailAddress": "jerry18@qq.com",
		"snsAddress": "jerry18@163.com",
		"ruleName": "人事業務_1031_18",
		"memo": "新規登録"
	}, {
		"userId": "019",
		"userName": "Jerry19",
		"mailAddress": "jerry19@qq.com",
		"snsAddress": "jerry19@163.com",
		"ruleName": "人事業務_1031_19",
		"memo": "新規登録"
	}, {
		"userId": "020",
		"userName": "Jerry20",
		"mailAddress": "jerry20@qq.com",
		"snsAddress": "jerry20@163.com",
		"ruleName": "人事業務_1031_20",
		"memo": "新規登録"
	}, {
		"userId": "021",
		"userName": "Jerry21",
		"mailAddress": "jerry21@qq.com",
		"snsAddress": "jerry21@163.com",
		"ruleName": "人事業務_1031_21",
		"memo": "新規登録"
	}, {
		"userId": "022",
		"userName": "Jerry22",
		"mailAddress": "jerry22@qq.com",
		"snsAddress": "jerry22@163.com",
		"ruleName": "人事業務_1031_22",
		"memo": "新規登録"
	}, {
		"userId": "023",
		"userName": "Jerry23",
		"mailAddress": "jerry23@qq.com",
		"snsAddress": "jerry23@163.com",
		"ruleName": "人事業務_1031_23",
		"memo": "新規登録"
	}, {
		"userId": "024",
		"userName": "Jerry24",
		"mailAddress": "jerry24@qq.com",
		"snsAddress": "jerry24@163.com",
		"ruleName": "人事業務_1031_24",
		"memo": "新規登録"
	}, {
		"userId": "025",
		"userName": "Jerry25",
		"mailAddress": "jerry25@qq.com",
		"snsAddress": "jerry25@163.com",
		"ruleName": "人事業務_1031_25",
		"memo": "新規登録"
	}, {
		"userId": "026",
		"userName": "Jerry26",
		"mailAddress": "jerry26@qq.com",
		"snsAddress": "jerry26@163.com",
		"ruleName": "人事業務_1031_26",
		"memo": "新規登録"
	}]

}

var CompanyList = {
	Rows: [{
		"companyCode": "000001",
		"companyName": "方正",
		"companyAlias": "方正",
		"administrator": "aaa",
		"phoneNumber": "11111111111",
		"url": "http://www.founder.com/"
	}, {
		"companyCode": "000002",
		"companyName": "东软",
		"companyAlias": "东软",
		"administrator": "bbb",
		"phoneNumber": "22222222222",
		"url": "http://www.neusoft.com/cn/"
	}, {
		"companyCode": "000003",
		"companyName": "浪潮",
		"companyAlias": "浪潮",
		"administrator": "ccc",
		"phoneNumber": "33333333333",
		"url": "http://www.inspur.com/"
	}, {
		"companyCode": "000004",
		"companyName": "华为",
		"companyAlias": "华为",
		"administrator": "ddd",
		"phoneNumber": "4444444444",
		"url": "https://www.vmall.com/huawei?mid=66421_201_1024121_0"
	}, {
		"companyCode": "000005",
		"companyName": "中兴",
		"companyAlias": "中兴",
		"administrator": "eee",
		"phoneNumber": "5555555555",
		"url": "http://www.zte.com.cn/china/"
	}, {
		"companyCode": "000006",
		"companyName": "南瑞",
		"companyAlias": "南瑞",
		"administrator": "fff",
		"phoneNumber": "666666666",
		"url": "http://www.sgepri.sgcc.com.cn/"
	}, {
		"companyCode": "000007",
		"companyName": "用友",
		"companyAlias": "用友",
		"administrator": "ggg",
		"phoneNumber": "777777777",
		"url": "http://www.yonyou.com/index.html?t=0.16577773276241925"
	}, {
		"companyCode": "000008",
		"companyName": "神州数码",
		"companyAlias": "神州数码",
		"administrator": "hhh",
		"phoneNumber": "888888888",
		"url": "http://www.digitalchina.com/"
	}, {
		"companyCode": "000009",
		"companyName": "金蝶",
		"companyAlias": "金蝶",
		"administrator": "iii",
		"phoneNumber": "999999999",
		"url": "http://www.kingdee.com/"
	}, {
		"companyCode": "526546",
		"companyName": "海康威视",
		"companyAlias": "海康威视",
		"administrator": "jjj",
		"phoneNumber": "544545445",
		"url": "http://www.hikvision.com/cn/index.html?jmode=j1"
	}, {
		"companyCode": "487897",
		"companyName": "航天信息",
		"companyAlias": "航天信息",
		"administrator": "kkk",
		"phoneNumber": "48454341",
		"url": "http://www.aisino.com/"
	}, {
		"companyCode": "987454",
		"companyName": "浙大网新",
		"companyAlias": "浙大网新",
		"administrator": "lll",
		"phoneNumber": "567421548",
		"url": "http://www.insigmagroup.com.cn/"
	}, {
		"companyCode": "544548",
		"companyName": "恒生",
		"companyAlias": "恒生",
		"administrator": "mmm",
		"phoneNumber": "453783",
		"url": "http://www.hundsun.com/"
	}, {
		"companyCode": "000004",
		"companyName": "华为",
		"companyAlias": "华为",
		"administrator": "ddd",
		"phoneNumber": "4444444444",
		"url": "https://www.vmall.com/huawei?mid=66421_201_1024121_0"
	}, {
		"companyCode": "000003",
		"companyName": "浪潮",
		"companyAlias": "浪潮",
		"administrator": "ccc",
		"phoneNumber": "33333333333",
		"url": "http://www.inspur.com/"
	}, {
		"companyCode": "000002",
		"companyName": "东软",
		"companyAlias": "东软",
		"administrator": "bbb",
		"phoneNumber": "22222222222",
		"url": "http://www.neusoft.com/cn/"
	}, {
		"companyCode": "000001",
		"companyName": "方正",
		"companyAlias": "方正",
		"administrator": "aaa",
		"phoneNumber": "11111111111",
		"url": "http://www.founder.com/"
	}]

}
var MemberList1 = {
	Rows: [{
		"group": "WEBSE結合試験２",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "WEBSE結合試験２",
		"chargeName": "担当者1",
		"role": "責任者"
	}]

}

var MemberList2 = {
	Rows: [{
		"group": "デモグループ03",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモグループ03",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモグループ03",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモグループ03",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモグループ03",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモグループ03",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモグループ03",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモグループ03",
		"chargeName": "担当者1",
		"role": "責任者"
	}]

}

var MemberList3 = {
	Rows: [{
		"group": "デモ用グループ",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "担当者1",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "CNdemo",
		"role": "担当者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "太郎",
		"role": "責任者"
	}, {
		"group": "デモ用グループ",
		"chargeName": "担当者1",
		"role": "責任者"
	}]

}